### ISSUE TITLE
Walkthrough - Export

### ISSUE THREAD

**Issue by HugoSchtr** [alix-tz/escriptorium-tutorial#13]
This issue has been created for keeping track of the writing of the __Export__ section.

- [x] Exporting models
- [x] Exporting annotations

**Comment by HugoSchtr** [comment]
@alix-tz I've made a first draft for the "exporting annotations" sections, see #34. Buuut, the gifs I created were made using my personal eScriptorium account, and not the demo account you created and used for the gifs in your import section. Do you think they have to be re-done (it's not a lot of work so it's not a problem).

**Comment by alix-tz** [comment]
As discussed live, if it is quick for you to remake the gif with the demo account, you can, otherwise, for a first version it's alright. It's really minor.
