### ISSUE TITLE
Walkthrough - Import 

### ISSUE THREAD

**Issue by alix-tz** [alix-tz/escriptorium-tutorial#17]
- [x] Import images
- [x] Import models
- [x] Import segmentation and transcription

Use https://lectaurep.hypotheses.org/documentation/escriptorium-tutorial-en as a basis

**Comment by HugoSchtr** [comment]
By the way, I wanted to ask you: what software do you use for creating GIFs?

**Comment by alix-tz** [comment]
The GIF creation is a very cumbersome process which needs to be optimized (I was too much of a perfectionist to use easier solutions): 
- recorded my screen
- took screen shots
- homogenized the size/frame with GIMP
-  loaded all the image on [Gif Maker](https://ezgif.com/maker)
- was carefully to find an okay speed (not too fast, not too slow either)

**Comment by alix-tz** [comment]
But in this case, I reused the GIF from the older tutorial.
