### ISSUE TITLE
Walkthrough - Annotate

### ISSUE THREAD

**Issue by alix-tz** [alix-tz/escriptorium-tutorial#18]
- [x] ~~Region and line types~~ edit: will actually be covered in "segment", I believe
- [x] Image annotations
- [x] Text annotations
- [ ] Annotation Components

**Comment by alix-tz** [comment]
I need feedback from users or from developpers to understand how "Annotation Components" work.

**Comment by HugoSchtr** [comment]
I will indeed cover region and line types in "Segment" :)
