### ISSUE TITLE
A walkthrough for the /admin/ page?

### ISSUE THREAD

**Issue by HugoSchtr** [alix-tz/escriptorium-tutorial#37]
Should we make a walkthrough for the administration page? Like giving some indication on how to manage an eScriptorium instance as an admin, giving rights to users, etc.

Or, is it unnecessary since it's based on Django site administration features, and thus users having access to it may already have general knowledge about it?

**Comment by alix-tz** [comment]
I would prefer to focus on the front end and consider that users who have access to admin sort of know what they are doing there., in particular considering that the back end should be used as little as possible. 🤔

**Comment by FloChiff** [comment]
I agree with Alix, considering all the things about admin are not the concern of most of the users so I don't think it is necessary to put it in the tutorial

**Comment by HugoSchtr** [comment]
I agree, but I was working on the collaborate walkthrough, and for inviting users, only administrators and users that have permission can do it!

I'll just mention it as part of the walkthrough but won't go into detail.

I'm closing the issue! :+1:
