### ISSUE TITLE
Help needed for "Virtual Keyboard" and "Text Normalization"

### ISSUE THREAD

**Issue by FloChiff** [alix-tz/escriptorium-tutorial#39]
I am working on #11 and I need a little more help on the two following parts, which I am not familiar with:
- [x] Virtual Keyboard
- [x] Text Normalization

**Comment by HugoSchtr** [comment]
Virtual keyboard walkthrough is done thanks to Alix!

For text normalization, do we want to write something in the transcribe walkthrough, like a note or something? Or maybe we should include something in the FAQ. 

Also, I have another question: is it relevant to the eScriptorium documentation? Isn't it more related to ATR in general and not to eScriptorium as an application?

**Comment by FloChiff** [comment]
We will need to have confirmation by Alix, but I am pretty sure that "Text normalization" is also done and is on the "Transcribe" walkthrough.

**Comment by alix-tz** [comment]
Yep! We can close this issue!
