### ISSUE TITLE
Create a "external doc" section

### ISSUE THREAD

**Issue by alix-tz** [alix-tz/escriptorium-tutorial#4]
- see docs in https://lectaurep.hypotheses.org/documentation/prendre-en-main-escriptorium
- and https://github.com/alix-tz/escriptorium-doc-finder

**Comment by HugoSchtr** [comment]
Should we close this issue as you mentioned external documentation in the FAQ?

**Comment by alix-tz** [comment]
I was considering making a whole dedicated page, but it can be a project for later. We can close this issue, indeed!

**Comment by alix-tz** [comment]
see #47
