### ISSUE TITLE
Some css work to do on the "github" footer

### ISSUE THREAD

**Issue by HugoSchtr** [alix-tz/escriptorium-tutorial#53]
The github footer, on the index, is hiding the last walkthrough "Administrator," I think we can mess with the css a bit to fix that!

![image](https://user-images.githubusercontent.com/74325901/221194861-6423b097-2886-40de-a81a-dc45438cca5e.png)

**Comment by alix-tz** [comment]
I had this issue at some point but I am unable to reproduce now...

**Comment by alix-tz** [comment]
Do you know which branch you were on when you took the screen shot? It's possible that I fixed it and that your branch was created before the fix made it to main. 🤔

**Comment by alix-tz** [comment]
Still unable to reproduce, so I guess it got fixed at some point

**Comment by HugoSchtr** [comment]
Same here! Well, good for us. :)

**Comment by alix-tz** [comment]
Spotted the bug: it happens when we are on the result page from Mkdocs' search engine, on the homepage, on contribute and on about.
